'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.GlobalStyle = undefined;

var _templateObject = _taggedTemplateLiteral(['\n        html{scroll-behavior: smooth;}\n        body, div, dl, dt, dd, ul, ol, li, pre, form, fieldset, blockquote,i,button, input, label{\n            padding:0;margin:0;list-style-type:none;font:normal 12px "Microsoft YaHei";word-break:break-all;}\n        \n        a{text-decoration:none;outline:none;}\n        a:link, a:hover, a:active, a:visited{text-decoration:none;}\n        a,button{transition: all 0.5s;cursor:pointer;}\n        a:hover,button:hover{transition: all 0.5s;}\n        h1,h2,h3,h4,h5,h6{margin:0;padding:0;}\n        fieldset,img{border:none}\n        ul, li, dl, dt, dd{list-style:none}\n        ol>li{list-style:disc;margin-left:15px;}\n        i{font-style:inherit;}\n        img,input{vertical-align:middle;}\n        table{border-collapse:collapse;border-spacing:0;}\n        address, caption, cite, code, dfn, em, strong, th, var{font-style:normal;font-weight:normal;}\n        caption, th{text-align:left;}\n        q:before, q:after{content:\'\';}\n        input,button,select,textarea{outline:none;box-sizing:border-box;}\n        input{background:none;border:0;outline:none;}\n        input:disabled{border:1px solid #ddd;background-color:#F5F5F5;color:#ACA899;}\n        input[type="reset"]::-moz-focus-inner,\n        input[type="button"]::-moz-focus-inner,\n        input[type="submit"]::-moz-focus-inner,\n        input[type="file"] > input[type="button"]::-moz-focus-inner{\n        border:none;padding:0;\n    }\n'], ['\n        html{scroll-behavior: smooth;}\n        body, div, dl, dt, dd, ul, ol, li, pre, form, fieldset, blockquote,i,button, input, label{\n            padding:0;margin:0;list-style-type:none;font:normal 12px "Microsoft YaHei";word-break:break-all;}\n        \n        a{text-decoration:none;outline:none;}\n        a:link, a:hover, a:active, a:visited{text-decoration:none;}\n        a,button{transition: all 0.5s;cursor:pointer;}\n        a:hover,button:hover{transition: all 0.5s;}\n        h1,h2,h3,h4,h5,h6{margin:0;padding:0;}\n        fieldset,img{border:none}\n        ul, li, dl, dt, dd{list-style:none}\n        ol>li{list-style:disc;margin-left:15px;}\n        i{font-style:inherit;}\n        img,input{vertical-align:middle;}\n        table{border-collapse:collapse;border-spacing:0;}\n        address, caption, cite, code, dfn, em, strong, th, var{font-style:normal;font-weight:normal;}\n        caption, th{text-align:left;}\n        q:before, q:after{content:\'\';}\n        input,button,select,textarea{outline:none;box-sizing:border-box;}\n        input{background:none;border:0;outline:none;}\n        input:disabled{border:1px solid #ddd;background-color:#F5F5F5;color:#ACA899;}\n        input[type="reset"]::-moz-focus-inner,\n        input[type="button"]::-moz-focus-inner,\n        input[type="submit"]::-moz-focus-inner,\n        input[type="file"] > input[type="button"]::-moz-focus-inner{\n        border:none;padding:0;\n    }\n']);

var _styledComponents = require('styled-components');

function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

var GlobalStyle = exports.GlobalStyle = (0, _styledComponents.createGlobalStyle)(_templateObject);